# WarrantyDog Production Docker Compose Configuration
# Optimized for production deployment with immediate availability

services:
  warrantydog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warrantydog-prod
    ports:
      - "3001:3001"
    volumes:
      # Only persist database data in production
      - warrantydog-prod-data:/workspace/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    working_dir: /workspace
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  warrantydog-prod-data:
