# WarrantyDog Simple Docker Compose Configuration
# Maximum compatibility - works on any Docker environment

services:
  warrantydog:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - warrantydog-data:/workspace/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  warrantydog-data:
