# WarrantyDog Docker Compose Configuration
# Provides a complete development environment with live reloading

version: '3.8'

services:
  warrantydog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warrantydog-app
    ports:
      - "3001:3001"  # WarrantyDog application port
    volumes:
      # Mount source code for live development
      - .:/workspace
      # Preserve node_modules in container
      - warrantydog-node-modules:/workspace/node_modules
      # Persist database data
      - warrantydog-data:/workspace/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    working_dir: /workspace
    restart: unless-stopped
    networks:
      - warrantydog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Development service (optional - for development with live reload)
  warrantydog-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warrantydog-dev
    ports:
      - "3002:3001"  # Different port for dev environment
    volumes:
      - .:/workspace
      - warrantydog-dev-modules:/workspace/node_modules
      - warrantydog-dev-data:/workspace/data
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    working_dir: /workspace
    restart: unless-stopped
    networks:
      - warrantydog-network
    profiles:
      - dev  # Only start with --profile dev
    command: ["bash", "-c", "npm install && node server.js"]

networks:
  warrantydog-network:
    driver: bridge
    name: warrantydog-network

volumes:
  warrantydog-node-modules:
    name: warrantydog-node-modules
  warrantydog-data:
    name: warrantydog-data
  warrantydog-dev-modules:
    name: warrantydog-dev-modules
  warrantydog-dev-data:
    name: warrantydog-dev-data
