# WarrantyDog Production Docker Compose Configuration
# Optimized for production deployment with immediate availability

version: '3.8'

services:
  warrantydog:
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: always
    # Remove development volumes for production
    volumes:
      - warrantydog-data:/workspace/data
    # Production-optimized health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  warrantydog-data:
    name: warrantydog-prod-data
