# WarrantyDog Docker Compose Configuration
# Provides a complete development environment with live reloading

version: '3.8'

services:
  warrantydog-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warrantydog-dev
    ports:
      - "8080:8080"
      - "3000:3000"  # Alternative port for testing
    volumes:
      # Mount source code for live development
      - .:/workspace
      # Preserve node_modules in container
      - /workspace/node_modules
      # Mount git config for commits (if available)
      # - ~/.gitconfig:/home/developer/.gitconfig:ro
      # Mount SSH keys for git operations (if available)
      # - ~/.ssh:/home/developer/.ssh:ro
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in containers
      - WATCHPACK_POLLING=true    # For webpack file watching
    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - warrantydog-network
    # Override default command to keep container running
    command: tail -f /dev/null

  # Optional: Add a simple web server for testing
  web-server:
    image: nginx:alpine
    container_name: warrantydog-web
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    depends_on:
      - warrantydog-dev
    networks:
      - warrantydog-network
    profiles:
      - web  # Only start with --profile web

networks:
  warrantydog-network:
    driver: bridge
    name: warrantydog-network

volumes:
  node_modules:
    name: warrantydog-node-modules
