version: '3.8'

services:
  warrantydog:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Database persistence for SQLite
      - warrantydog-data:/app/data

volumes:
  warrantydog-data:
    driver: local
